// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version = "v0.9.2"
	GitCommit = "a96a2a2" // the commit JUST BEFORE the release
	VersionDate = "2020-06-28 09:40" // UTC
)

