// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.9.5"
	GitCommit   = "bfb2b5d"          // the commit JUST BEFORE the release
	VersionDate = "2023-08-27 22:52" // UTC
)
