#!/bin/bash

if [ -z "$GOPATH" ]
then
	export GOPATH="$HOME/go"
fi

# this should get all your env settings:
source $HOME/.bash_profile

# in general don't want to be using modules for development work:
export PATH="$GOPATH/bin:$PATH"

"$GOPATH/bin/gopix" "$@" > "$HOME/Library/gopix/gopix.log" 2>&1

