// Code generated by "stringer -type=ImgGridSignals"; DO NOT EDIT.

package imgrid

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ImgGridDoubleClicked-0]
	_ = x[ImgGridInserted-1]
	_ = x[ImgGridDeleted-2]
	_ = x[ImgGridSignalsN-3]
}

const _ImgGridSignals_name = "ImgGridDoubleClickedImgGridInsertedImgGridDeletedImgGridSignalsN"

var _ImgGridSignals_index = [...]uint8{0, 20, 35, 49, 64}

func (i ImgGridSignals) String() string {
	if i < 0 || i >= ImgGridSignals(len(_ImgGridSignals_index)-1) {
		return "ImgGridSignals(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImgGridSignals_name[_ImgGridSignals_index[i]:_ImgGridSignals_index[i+1]]
}

func (i *ImgGridSignals) FromString(s string) error {
	for j := 0; j < len(_ImgGridSignals_index)-1; j++ {
		if s == _ImgGridSignals_name[_ImgGridSignals_index[j]:_ImgGridSignals_index[j+1]] {
			*i = ImgGridSignals(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: ImgGridSignals")
}
